# Default values for serverclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of server loadBalancers & deployments
serverInstanceCount: 1
# Number of client deployments 
clientInstanceCount: 0

nameOverride: ""
fullnameOverride: ""
azureRegion: "westus2"
nodeSelector: 
  kubernetes.io/os: windows


deployment:
  client:
      clientReplicaCount: 1
      clientCommand: ["/client.exe", "-p", "4444", "-c", "10", "-i"]
      requestsArg: 600
      requestDelayArg: 1000
  server:
    serverCommand: ["/server.exe", "-p", "4444", "-swt", "300", "-awt", "200"]
    serverReplicaCount: 2
    nodeAffinity: ""
    topologyKey: testtype
  image:
    registry: princepereira
    repository: tcp-client-server
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: probe
  auth:
    enabled: false
  imagePullSecrets: []
  podAnnotations: {}
  preStopHookCommand: ["curl", "http://127.0.0.1:8090/kill", "-v"]
  terminationGracePeriodSeconds: 600
  podSecurityContext: {}
  tolerations: []
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: LoadBalancer
  tcpPort: 4444 # DO NOT CHANGE THIS. TODO: Client is hardcoded to port 4444.
  udpPort: 4445
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Local