{{- range $i, $e := until (int .Values.serverInstanceCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ (include "serverclient.fullname" $)}}-{{ $i }}
  labels:
    {{- include "serverclient.labels" $ | nindent 4 }}-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ $.Values.deployment.server.serverReplicaCount }}
  selector:
    matchLabels:
      {{- include "serverclient.selectorLabels" $| nindent 6 }}-{{ $i }}
  template:
    metadata:
      annotations:
        {{- toYaml $.Values.deployment.podAnnotations | nindent 8 }}
      labels:
        {{- include "serverclient.selectorLabels" $ | nindent 8 }}-{{ $i }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.deployment.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml $.Values.deployment.podSecurityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ $.Chart.Name }}-{{ $i }}
          image: "{{ $.Values.deployment.image.registry }}/{{ $.Values.deployment.image.repository }}:{{ $.Values.deployment.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.deployment.image.pullPolicy }}
          resources:
            {{- toYaml $.Values.deployment.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          lifecycle:
            preStop:
              exec:
                command: 
                {{- toYaml $.Values.deployment.preStopHookCommand | nindent 18 }}
          {{- if $.Values.deployment.server.serverCommand }}
          command:
            {{- toYaml $.Values.deployment.server.serverCommand | nindent 12 }}
          {{- end }}
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      terminationGracePeriodSeconds: {{ $.Values.deployment.terminationGracePeriodSeconds }}
      affinity: 
        {{- toYaml $.Values.deployment.affinity | nindent 8 }}
      tolerations:
        {{- toYaml $.Values.deployment.tolerations | nindent 8 }}
{{- end }}